name: "file updater"
on:
  workflow_dispatch

jobs:
  updateversion:
    name: Update HR version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update file
        run: |
          echo "test: $(date)" > files/test.txt
          echo "test: $(date)" > files/test2.txt
          rm test.txt
          
          git add .
          
          export GITHUB_REPO="playground"
          export GITHUB_OWNER="apollorion"
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          python ./.github/scripts/file_updater/updater.py
