name: "file updater"
on:
  workflow_dispatch:
    inputs:
      files:
        required: true
        type: string

permissions: write-all

jobs:
  updateversion:
    name: Update HR version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update file
        run: |   
          repo_owner="apollorion"
          repo_name="playground"
          
          set -e
          
          files="${{ inputs.files }}"      
          echo $files | sed -n 1'p' | tr ',' '\n' | while read file; do
            echo "Updating file: $file"
          
            blob_sha=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$repo_owner/$repo_name/contents/$file | jq -r '.sha')
          
            # get the files new content
            new_content=$(cat $file)
            new_content="$new_content\n$(date)"
          
            # Base64 encode the new content
            new_content_base64=$(echo -n $new_content | base64)
          
            # Update the file with github api
            curl -i -X PUT \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"message\":\"feat($file): update file contents\",\"sha\":\"${blob_sha}\",\"committer\":{\"name\":\"github-file-updater\",\"email\":\"no-reply@github.com\"},\"content\":\"${new_content_base64}\"}" \
              https://api.github.com/repos/$repo_owner/$repo_name/contents/$file
          done
