name: "file updater"
on:
  workflow_dispatch:
    inputs:
      files:
        required: true
        type: string
      newVersion:
        required: true
        type: string

jobs:
  updateversion:
    name: Update HR version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          
          files="${{ inputs.files }}"      
          echo $files | sed -n 1'p' | tr ',' '\n' | while read file; do
            echo "Updating file: $file"
          
            # get the files new content
            new_content=$(cat $file)
            new_content="$new_content\n$(date)"
          
            # Base64 encode the new content
            new_content_base64=$(echo -n $new_content | base64)
          
            # Update the file with github api
            curl -i -X PUT \
              -H "Authorization: token $GITHUB_TOKEN" \
              -d "{\"message\":\"feat($file): update file contents\",\"committer\":{\"name\":\"github-file-updater\",\"email\":\"no-reply@github.com\"},\"content\":\"${new_content_base64}\"}" \
              https://api.github.com/repos/apollorion/$GITHUB_REPOSITORY/contents/$file
          done
